### ISSUE TITLE
NullPointerException thrown when minimum required configuration values don't exist

### ISSUE THREAD

**Issue by wlaforest** [confluentinc/cyber#4]
When the schema registry URL was not provided a null pointer exception was thrown during intialization:  

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1301)
	at java.base/java.util.Properties.setProperty(Properties.java:229)
	at io.confluent.sigmarules.rules.SigmaRulesStore.initialize(SigmaRulesStore.java:51)
	at io.confluent.sigmarules.rules.SigmaRulesStore.<init>(SigmaRulesStore.java:44)
	at io.confluent.sigmarules.rules.SigmaRulesFactory.initialize(SigmaRulesFactory.java:61)
	at io.confluent.sigmarules.rules.SigmaRulesFactory.<init>(SigmaRulesFactory.java:48)
	at io.confluent.sigmarules.SigmaStreamsApp.createSigmaRules(SigmaStreamsApp.java:55)
	at io.confluent.sigmarules.SigmaStreamsApp.<init>(SigmaStreamsApp.java:46)
	at io.confluent.sigmarules.SigmaStreamsApp.main(SigmaStreamsApp.java:120)

**Comment by wlaforest** [comment]
Fixed by https://github.com/confluentinc/cyber/pull/5
